name: Process Documentation

on:
  push:
    paths:
      - 'main.tex'

jobs:
  process-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert LaTeX to Markdown
      run: |
        sed -e 's/\\begin{verbatim}/```/g' \
            -e 's/\\end{verbatim}/```/g' \
            "main.tex" > "main.md"
          
    - name: Commit Markdown changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add main.md
        git commit -m "Auto-convert LaTeX to Markdown" || echo "No changes to commit"

    - name: Convert Markdown to HTML
      run: |
        npm install marked
        npx marked main.md > content.html

        echo '<!DOCTYPE html>
        <html>
        <head>
          <title>Documentation</title>
          <meta charset="UTF-8">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown.min.css">
          <style>
            .markdown-body {
              box-sizing: border-box;
              min-width: 200px;
              max-width: 980px;
              margin: 0 auto;
              padding: 45px;
            }
          </style>
        </head>
        <body>
          <article class="markdown-body">' > index.html
        
        cat content.html >> index.html
        
        echo '</article>
        </body>
        </html>' >> index.html

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      
    - name: Push all changes
      run: git push